# -*- coding: utf-8 -*-
"""Body mass Calulator .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NdIFumn7WprEPC7_NtoA1PpHTOk2Y6Br
"""







#this programe is about to find the actual body mass means its a body mass calulator

import math #Here we import math laborary
print("Welcome to Body Mass Calculator")

name = input("Enter your name : ")
print(name)

#here we do typecasting from string to float
weight  = float(input("Enter your weight in kg's: "))
hight = float(input("Enter your Hight in Meter's: "))

#here we set the formula for the body mass calculator
BMC = weight / hight**2
print("Your body mass is: ", BMC)

#here we Set the conditions of the body
if BMC < 18:
  print("you are underweight")
elif BMC <= 24:
  print("You have a normal weight")
elif BMC > 24:
  print("You are overwight")

