# -*- coding: utf-8 -*-
"""Find_len_and _typeAnd Casting.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NdIFumn7WprEPC7_NtoA1PpHTOk2Y6Br
"""



#in this programe we find the lenth and type of the the variable and input and
#also we a type casting in it
name = (input("Enter you name Please : "))
print ("your name lenghts is: ", (len(name)), " ", type(name))

name_cating = int(len(name))
print("your name is ", name , "and your name has ", name_cating ," charachters")
print("the type of your name is ", type(name), "and the type of your lenght is ", type(name_cating))