# -*- coding: utf-8 -*-
"""Roler coster problem Using If else Condition .ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c73UxQ2AA-fDLewaMWkCBTVXXGBjSnBY
"""



#Roler coster problem Using If else Condition

hight = int(input("Enter your hight in Cm's Please: "))
print("Your Hight is: ",hight)

if hight == 120:
  print(f"Your Hight is {hight} you can Ride the Rolercoster.")

elif hight >= 121 and hight < 150:
  print(f"Your Hight is {hight} you can Ride the Rolercoster.")

elif hight > 150:
  print(f"Your Hight is {hight} so Sorry you are not allowed to Ride the Rolercoster.")

else:
  print("Sorry you are not allowed to Ride the Rolercoster.")