# -*- coding: utf-8 -*-
"""Simple Calculator_ Using _Ifelse_Condition.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c73UxQ2AA-fDLewaMWkCBTVXXGBjSnBY
"""

#simple calulator using if else condition
# in this programe we use Numarical Oprator, typecasting , if else condition, and fprint type

print("Press 1 For Divistion: ")
print("Press 2 For Multiplication: ")
print("press 3 For addtion: ")
print("Press 4 For subtraction: ")
print("Press 5 For modules: ")
print("Press 6 For root: ")

choice = int(input("Enter your choice: "))

num1 = float(input("Enter The Frist Number: "))
num2 = float(input("Enter the second Number: "))

if choice == 1:
  division = num1 / num2
  print(f"Frist Number you Enter {num1} Second Number You Enter {num2} and your Division is {division}")

elif choice == 2:
  multip = num1 * num2
  print(f"Frist Number you Enter {num1} Second Number You Enter {num2} and your Multiplication is {multip}")

elif choice == 3:
  add = num1 + num2
  print(f"Frist Number you Enter {num1} Second Number You Enter {num2} and your Addition is {add}")

elif choice == 4:
  subtrc = num1 - num2
  print(f"Frist Number you Enter {num1} Second Number You Enter {num2} and your subtraction is {subtrc}")

elif choice == 5:
  modules = num1 % num2
  print(f"Frist Number you Enter {num1} Second Number You Enter {num2} and your modules is {modules}")

elif choice == 6:
  root = num1 ** num2
  print(f"Frist Number you Enter {num1} Second Number You Enter {num2} and your root is {root}")