# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c73UxQ2AA-fDLewaMWkCBTVXXGBjSnBY
"""

#numarical oprator

num1 = float(input("Enter The Frist Number: "))
num2 = float(input("Enter the second: "))

division = num1 / num2
print(division)

Multipli = num1 * num2
print(Multipli)

add = num1 + num2
print(add)

subtract = num1 - num2
print(subtract)

mudoles = num1 % num2
print(mudoles)

root = num1 ** num2
print(root)